---
language: node_js
node_js:
  - 10.15.0

dist: trusty

cache:
  directories:
    - node_modules

install:
  - npm install -g npm@6.4.1
  - npm install

script:
  - ./scripts/ci-check.sh

notifications:
  email:
    on_success: 'change'
    on_failure: 'change'
